import os
import joblib
import numpy as np
import pandas as pd
import tensorflow as tf
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn

app = FastAPI(title="Three-Stage Sleep Analysis API")

# Enable CORS so your live React dashboard can communicate with this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Define the data structure expected from your React frontend
class PatientInput(BaseModel):
    Gender: str
    Occupation: str
    BMI_Category: str  # Maps to 'BMI Category'
    Age: int
    Sleep_Duration: float  # Maps to 'Sleep Duration'
    Quality_of_Sleep: int  # Maps to 'Quality of Sleep'
    Physical_Activity_Level: int  # Maps to 'Physical Activity Level'
    Stress_Level: int  # Maps to 'Stress Level'
    Heart_Rate: int  # Maps to 'Heart Rate'
    Daily_Steps: int  # Maps to 'Daily Steps'
    Blood_Pressure: str  # Format: "120/80"

# Global variables to hold our loaded models and preprocessor
model_stage1 = None
model_stage2 = None
preprocessor = None

LABEL_MAP = {0: 'None', 1: 'Insomnia', 2: 'Sleep Apnea', 3: 'Narcolepsy', 4: 'REM Behavior Disorder'}

@app.on_event("startup")
def load_artifacts():
    global model_stage1, model_stage2, preprocessor
    try:
        # Load the saved models and preprocessor generated by your pipeline
        preprocessor = joblib.load('models/preprocessor.pkl')
        model_stage1 = tf.keras.models.load_model('models/sleep_stage_classifier.h5')
        model_stage2 = tf.keras.models.load_model('models/disorder_classifier.h5')
        print("All models and preprocessors loaded successfully!")
    except Exception as e:
        print(f"Error loading models: {e}. Ensure you have run the training pipeline first.")

def generate_recommendations(disorder, stress_level, sleep_duration):
    """Rule-based advisory engine translating predictions into actionable insights."""
    recommendations = []
    
    if disorder == 'Insomnia':
        recommendations.extend([
            "Maintain a strict, consistent sleep schedule even on weekends.",
            "Limit caffeine and screen exposure at least 2 hours before bed.",
            "Try progressive muscle relaxation techniques before sleeping."
        ])
    elif disorder == 'Sleep Apnea':
        recommendations.extend([
            "Consider sleeping on your side instead of your back to keep airways open.",
            "Consult a specialist for a potential CPAP therapy evaluation.",
            "Avoid alcohol or heavy meals close to bedtime."
        ])
    elif disorder in ['Narcolepsy', 'REM Behavior Disorder']:
        recommendations.extend([
            "Schedule short, planned daytime naps (15-20 mins) to manage sudden sleepiness.",
            "Ensure your bedroom environment is clear of sharp objects to maintain physical safety.",
            "Follow up closely with a neurological or sleep specialist."
        ])
    else:
        recommendations.append("Your sleep metrics look healthy! Keep maintaining your current routine.")

    if stress_level > 6:
        recommendations.append("High stress detected: Consider integrating 10 minutes of mindfulness or deep breathing exercises daily.")
    if sleep_duration < 6.5:
        recommendations.append("Sleep duration is below recommended levels. Target extending sleep time by 30 minutes this week.")
        
    return recommendations

@app.get("/")
def health_check():
    return {"status": "online", "message": "Sleep Analysis Model Server is Live!"}

@app.post("/predict")
def predict_sleep_disorder(data: PatientInput):
    if preprocessor is None or model_stage1 is None or model_stage2 is None:
        return {"error": "Models are not fully initialized yet."}
    
    # 1. Parse Blood Pressure just like the training pipeline does
    try:
        systolic, diastolic = map(int, data.Blood_Pressure.split('/'))
    except Exception:
        return {"error": "Invalid Blood Pressure format. Use 'Systolic/Diastolic' format (e.g., '120/80')."}

    # 2. Reconstruct dataframe structure to feed into the preprocessor pipeline
    input_dict = {
        'Age': [data.Age],
        'Sleep Duration': [data.Sleep_Duration],
        'Quality of Sleep': [data.Quality_of_Sleep],
        'Physical Activity Level': [data.Physical_Activity_Level],
        'Stress Level': [data.Stress_Level],
        'Heart Rate': [data.Heart_Rate],
        'Daily Steps': [data.Daily_Steps],
        'Systolic_BP': [systolic],
        'Diastolic_BP': [diastolic],
        'Gender': [data.Gender],
        'Occupation': [data.Occupation],
        'BMI Category': [data.BMI_Category]
    }
    
    df_input = pd.DataFrame(input_dict)
    
    # 3. Transform input features using the saved preprocessor
    processed_features = preprocessor.transform(df_input)
    
    # 4. Step 1: Stage 1 Inference (Binary REM/NREM related baseline classification)
    pred_stage1 = model_stage1.predict(processed_features)[0][0]
    is_rem_disorder = bool(pred_stage1 > 0.5)
    
    # 5. Step 2: Stage 2 Inference (Multi-class specific disorder classification)
    pred_stage2_probs = model_stage2.predict(processed_features)[0]
    predicted_class_idx = int(np.argmax(pred_stage2_probs))
    predicted_disorder = LABEL_MAP.get(predicted_class_idx, "Unknown")
    confidence = float(pred_stage2_probs[predicted_class_idx])
    
    # 6. Step 3: Run rule-based advisory engine
    insights = generate_recommendations(predicted_disorder, data.Stress_Level, data.Sleep_Duration)
    
    return {
        "stage1_rem_alert": is_rem_disorder,
        "prediction": predicted_disorder,
        "confidence": confidence,
        "probabilities": {LABEL_MAP[i]: float(prob) for i, prob in enumerate(pred_stage2_probs)},
        "actionable_insights": insights
    }

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run("main:app", host="0.0.0.0", port=port)
